name: 'PR Tasks Completed Check'
on: 
  pull_request:
    types: [opened, edited]



jobs:
  task-check:
    runs-on: ubuntu-latest
    permissions: 
      actions: write
      checks: write
      pull-requests: write
    steps:
      - uses: chromaui/task-completed-checker-action@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
